name: Release

on:
  push:
    branches:
      - main

env:
  node_version: 19

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install node
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      # Cache modules
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: .npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci --cache .npm --prefer-offline

      - run: npm run build

      # TODO - can we combine these steps?
      # Get the version from built 'module.json'
      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Get Compatibility
        id: read_foundry_compatibility
        run: |
          # Use jq to extract multiple values from the JSON file
          MIN_FOUNDRY_COMPATIBILITY =$(jq -r '.compatibility.minimum' ./src/module.json)
          MAX_FOUNDRY_COMPATIBILITY=$(jq -r '.compatibility.maximum' ./src/module.json)
          VERIFIED_FOUNDRY_COMPATIBILITY=$(jq -r '.compatibility.verified' ./src/module.json)
          
          # Set each value as an output variable
          echo "minFoundryCompatibility=$MIN_FOUNDRY_COMPATIBILITY" >> $GITHUB_OUTPUT
          echo "maxFoundryCompatibility=$MAX_FOUNDRY_COMPATIBILITY" >> $GITHUB_OUTPUT
          echo "verifiedFoundryCompatibility=$VERIFIED_FOUNDRY_COMPATIBILITY" >> $GITHUB_OUTPUT

      # Useful only for the template so we can leave the manifest and download urls empty
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_latest
        uses: microsoft/variable-substitution@v1
        with:
          files: './dist/module.json'
        env:
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/latest/download/module.zip

      # Create a zip file with all files required by the module to add to the release
      - name: Zip Latest Release
        working-directory: ./dist
        run: zip -r ../module.zip ./*

      # Update the 'latest' release
      - name: Update Latest Release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'main')
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json, ./module.zip'
          tag: latest
      
      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: './dist/module.json'
        env:
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get-version.outputs.version}}/module.zip
      
      # Create a zip file with all files required by the module to add to the release
      - name: Zip Version Release
        working-directory: ./dist
        run: zip -r ../module.zip ./*

      # TODO - moved this up for testing, move below "Create Github Version Release" when ready
      # The Foundry VTT release process is a separate one from the GitHub release process
      - name: Create Foundry Release
        run: node ./.github/workflows/create-foundry-release.js
        env:
          foundryPackageReleaseAuthToken: ${{ secrets.FVTT_PACKAGE_RELEASE_AUTH_TOKEN }}
          moduleVersion: ${{ steps.get-version.outputs.version }}
          notesUrl: https://github.com/${{github.repository}}/releases/tag/release-${{steps.get-version.outputs.version}}
          url: https://github.com/${{github.repository}}
          manifestUrl: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get-version.outputs.version}}/module.zip
          minimumCompatibility: ${{ steps.read_compatibility.outputs.minFoundryCompatibility }}
          maximumCompatibility: ${{ steps.read_compatibility.outputs.maxFoundryCompatibility }}
          verifiedCompatibility: ${{ steps.read_compatibility.outputs.verifiedFoundryCompatibility }}


      # Create a release for this specific version
      - name: Create Github Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false # set this to false if you want to prevent updating existing releases
          name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './dist/module.json,./module.zip'
          tag: ${{ steps.get-version.outputs.version }}